services:
  minio-api:
    pull_policy: build
    container_name: minio-api
    build: /minio-api/
    image: minio-api:latest
    ports:
      - "8080:8080"

  mail-sender:
    pull_policy: build
    container_name: mailsender-api
    build: /mailsender/
    image: mailsender:latest
    ports:
      - "8081:8081"

  kafka-listener:
    pull_policy: build
    container_name: kafka-listener
    build: /kafka-listener/
    image: kafka-listener:latest

#  google-oauth2:
#    pull_policy: build
#    container_name: google-oauth2
#    build: /google-oauth2/
#    image: google-oauth2:latest
#    ports:
#      - "8082:8082"