services:
  minio-api:
    pull_policy: build
    container_name: minio-api
    build: /minio-api/
    image: minio-api:latest
    ports:
      - "8080:8080"

  mail-sender:
    pull_policy: build
    container_name: mailsender-api
    build: /mailsender/
    image: mailsender:latest
    ports:
      - "8081:8081"

  kafkamailsender:
    pull_policy: build
    container_name: kafkamailsender-api
    build: /kafkamailsender
    image: kafkamailsender:latest
    ports:
      - "8082:8082"

  kafka-listener:
    pull_policy: build
    container_name: kafka-listener
    build: /kafka-listener/
    image: kafka-listener:latest
    ports:
      - "8083:8083"

#
#  google-oauth2:
#      pull_policy: build
#      container_name: google-oauth2
#      build: /google-oauth2/
#      image: google-oauth2:latest
#      ports:
#        - "8084:8084"

#  gmail-api:
#    pull_policy: build
#    container_name: gmail-api
#    build: /gmail-api/
#    image: gmail-api:latest
#    ports:
#      - "8085:8085"