services:
  minio-api:
    pull_policy: build
    container_name: minio-api
    build: /minio-api/
    ports:
      - "8080:8080"

  mail-sender:
    pull_policy: build
    container_name: mailsender-api
    build: /mailsender/
    ports:
      - "8081:8081"

  kafka-listener:
    pull_policy: build
    container_name: kafka-listener
    build: /kafka-listener/
    ports:
      - "8083:8083"

  google-oauth2:
    pull_policy: build
    container_name: google-oauth2
    build: /google-oauth2/
    ports:
      - "8084:8084"

#    mysql-server:
#      pull_policy: build
#      container_name: mysql-server
#      build:
#        context: /
#        dockerfile: Dockerfile.mysqlserver
#      image: mysql-server:latest
#      ports:
#        - "8084:8084"


