services:
  minio-api:
    pull_policy: build
    container_name: minio
    build: /minio-api/
    environment:
      MINIO_ENDPOINT: "http://118.71.99.251:9095"
      MINIO_ACCESS_KEY: "ERnGCPDwwkhCObagKdiA"
      MINIO_SECRET_KEY: "zf1yGIuCP2JVw6ssVubn7b6ZtUkMRHtENWtkgvl1"
    ports:
      - "8080:8080"

  mailsender:
    pull_policy: build
    container_name: mailsender
    build: /mailsender/
    environment:
      DEFAULT_MAIL_USERNAME: "danghieu231299@gmail.com"
      DEFAULT_MAIL_PASSWORD: "jpce tgit jvpv pstq"
      BOOTSTRAP_SERVERS_CONFIG: "118.71.99.251:9092"
    ports:
      - "8081:8081"

  kafka-listener:
    pull_policy: build
    container_name: kafka-listener
    build: /kafka-listener/
    environment:
      BOOTSTRAP_SERVERS_CONFIG: "118.71.99.251:9092"
    ports:
      - "8082:8082"




