FROM mysql:latest

# Set environment variables for MySQL
# Replace 'your_password' with a strong password
ENV MYSQL_USER=root
ENV MYSQL_ROOT_PASSWORD=admin
ENV MYSQL_PASSWORD=your_user_password

# Expose the MySQL port
EXPOSE 3306

# Command to run MySQL server
CMD ["mysqld"]